import { trailContent } from '../trail';
import type { Landmark } from '../trail/types';

export const quotes = {
  intro: { text: "I saw Indians smash my dear parents' heads on the pillow next to mine... I have seen some reddish work done at night.", speaker: 'Abigail Williams', act: 'Act I', context: "Abigail recalls the violence she witnessed while threatening the other girls to keep quiet." },
  name: { text: 'I have given you my soul; leave me my name!', speaker: 'John Proctor', act: 'Act IV', context: "Proctor refuses to let the court display his signed confession. His words ask what it costs to survive by lying." },
  hysteria: { text: 'The little crazy children are jangling the keys of the kingdom, and common vengeance writes the law!', speaker: 'John Proctor', act: 'Act II', context: "Proctor sees neighbors using the accusations to settle old grudges." },
  neutral: { text: 'A person is either with this court or he must be counted against it, there be no road between.', speaker: 'Danforth', act: 'Act III', context: "Danforth insists that anyone who does not support the court must be against it." },
  accuse: { text: 'Is the accuser always holy now? Were they born this morning as clean as God’s fingers?', speaker: 'John Proctor', act: 'Act II', context: "Proctor asks why the court believes accusers without questioning their motives." },
} as const;
export type QuoteId = keyof typeof quotes;

const objects = [
  [ ['docket','The daily docket',"Eight cases are scheduled, one each day. Your next visitor will come to the bench. You can adjourn any hearing to look for evidence before you rule."], ['standard','The court’s old rulebook',"The rulebook says a charge needs evidence that can be checked. Look for money changing hands, statements that were copied, and disputes that began before the accusation. Compare your findings in Record."], ['hearth','The public benches',"Your neighbors sit close together and speak in whispers. You recognize most of them. They used to greet you in the street; now they watch to see whose side you will take."], ['seal','The court seal',"The seal marks a statement as part of the court record. It says nothing about whether the statement is true. If witnesses speak in public, others can notice when their words are changed."] ],
  [ ['deed','The land register',"The register gives Merrin the first chance to buy Rook’s field if the court seizes it. He stands to gain from her conviction."], ['offer','The rejected offer',"Rook turned down Merrin’s offer to buy her field. Two days later, he accused her of witchcraft. The dates appear in separate records."], ['copy','The copied testimony',"Two witness statements describe the same strange sight in exactly the same words. Even a crossed-out phrase appears in both copies."], ['clock','The clerk’s timebook',"The clerk noted that the second witness arrived after the event and copied the first statement at his desk. The two accounts did not come from separate observations."] ],
  [ ['grudge','The old complaint',"Last winter, the apothecary appealed a fine imposed by the reeve and won. His new accusation repeats several insults from that earlier dispute."], ['petition','The reeve’s petition',"Before he accused the apothecary of witchcraft, the reeve asked the court to stop hearing her appeals. He had already tried to keep her from speaking."], ['bench','The witness bench',"A farmer is willing to testify, but only where her neighbors can hear her. She worries that a private statement could be changed before it reaches the court."], ['notice','The town notice',"A notice urges residents to report anyone who questions the accusations. Someone has written your name in the margin."] ],
];
const locations = [{id:'chamber',title:'Judge’s chamber',base:0},{id:'archive',title:'Records room',base:1},{id:'square',title:'Petition gallery',base:2}];
export const townMaps: Landmark[] = locations.map((place,index)=> {
  const base=trailContent.landmarks[place.base];
  return {...base,id:place.id,title:place.title,spawn:place.id==='chamber'?{x:9,y:4}:base.spawn,interactions:objects[index].map(([id,title,body],i)=>({...base.interactions[i],...(place.id==='chamber'?[{x:15,y:6},{x:9,y:3},{x:3,y:5},{x:15,y:3}][i]:{}),id,title,body,encounterId:id,basis:'invented',actReference:'Original town fiction inspired by The Crucible',sourceNote:'This citizen, record and scene are invented; they are not Miller’s dialogue.'}))};
});
export const connections = [
  { id:'motive', title:'Who profits?', clues:['deed','offer'], location:'Records room', correct:"Merrin wants the land. His accusation needs closer checking.", wrong:'Wanting the land proves the accuser is a witch.', feedback:"The offer and land register show that Merrin stands to gain from a conviction. That gives you a reason to question his accusation. It does not prove that he is a witch." },
  { id:'source', title:"Two witnesses or one source?", clues:['copy','clock'], location:'Records room', correct:"One witness copied the other. This is only one account.", wrong:'Matching statements must be true.', feedback:"The timebook shows that one witness copied the other. These are two statements, but only one account of what happened." },
  { id:'grudge', title:'What came before the charge?', clues:['grudge','petition'], location:'Petition gallery', correct:"The reeve may want revenge. We still need proof of his charge.", wrong:'A long-running dispute proves the accused guilty.', feedback:"The complaint and petition suggest that the reeve wants revenge. His accusation needs proof, just like anyone else’s." },
] as const;
export type ConnectionId = typeof connections[number]['id'];
export interface Case { quote:QuoteId; quoteConnection:string; id:string; title:string; text:string; kind:'accusation'|'neutral'|'record'|'final'; proof:ConnectionId; defend:string; accuse:string }
export const cases: readonly Case[] = [
  {quote:'hysteria',quoteConnection:"Merrin could use the accusation to get the land Rook refused to sell him.",id:'field',title:'The field beyond the fence',text:"Merrin accuses his neighbor, Rook, of cursing the stones along their property line. Before you can question him, he asks whether her field will be put up for sale if she is condemned.",kind:'accusation',proof:'motive',defend:'Defend Rook',accuse:'Accuse Rook to protect yourself'},
  {quote:'accuse',quoteConnection:"The witnesses agree, but you still need to know whether they each saw what happened.",id:'miller',title:'Two voices in perfect agreement',text:"Two witnesses claim they saw the miller speaking to a shadow after dark. Their statements match word for word. The crowd takes this as proof, but you have not yet heard how either statement was taken.",kind:'accusation',proof:'source',defend:'Defend the miller',accuse:'Accept the accusation'},
  {quote:'hysteria',quoteConnection:"The reeve may be using the court to settle an old grudge.",id:'apothecary',title:'An old debt comes due',text:"The reeve, a local official, accuses the apothecary of witchcraft. Last winter, she persuaded the court to overturn a fine he had imposed. When you ask about their dispute, he insists it has nothing to do with his accusation.",kind:'accusation',proof:'grudge',defend:'Defend the apothecary',accuse:'Side with the reeve'},
  {quote:'neutral',quoteConnection:"The elders treat anyone who questions them as an enemy.",id:'neutrality',title:'The town demands your loyalty',text:"The elders demand to know whose side you are on. They say that questioning an accuser undermines the court. You can insist on public questioning or try to stay out of the dispute.",kind:'neutral',proof:'source',defend:'Require accusers to answer in public',accuse:'Try to stay neutral'},
  {quote:'neutral',quoteConnection:"The clerk is in trouble for keeping evidence that the elders would rather ignore.",id:'clerk',title:'The clerk is accused of doubt',text:"The clerk kept the original witness statements, including the passages that contradict one another. Now the elders accuse him of helping the suspects. If you condemn him, there may be no one left to explain how the statements were changed.",kind:'accusation',proof:'source',defend:'Defend the clerk and preserve the originals',accuse:'Accuse the clerk to save your position'},
  {quote:'accuse',quoteConnection:"If everyone can read the statements, they can judge whether the accusers deserve to be believed.",id:'record',title:'Who gets to read the record?',text:"The elders want to seal the court records. You can agree, or you can let the town read the evidence and hear from the witnesses. This is also your chance to publicly correct one accusation you supported.",kind:'record',proof:'motive',defend:'Publish and correct the public record',accuse:'Seal the record to protect yourself'},
  {quote:'accuse',quoteConnection:"The farmer has evidence that challenges an accuser. The court must decide whether to hear her.",id:'witness',title:'The witness who will not whisper',text:"A farmer says she saw someone copying the witness statements. She wants to testify in public. The reeve calls her a liar and demands that you charge her too. Will you let her speak?",kind:'accusation',proof:'grudge',defend:'Defend her right to testify',accuse:'Silence her with an accusation'},
  {quote:'name',quoteConnection:"The elders offer to spare you if you put your name to a lie.",id:'name',title:'Your name beneath their words',text:"The elders place a confession before you. You know it is false, but they promise to spare your life if you sign. If you refuse, you will have to rely on the evidence and witnesses you brought before the town.",kind:'final',proof:'source',defend:'Refuse and let the public record answer',accuse:'Lie and sign to save yourself'},
];
