import { useCallback, useEffect, useRef, useState } from 'react';
import { cases, connections, quotes, townMaps } from '../content/judge';
import { initialJudge, judgeStanding, judgeTransition, rulingHint } from '../engine/judge/game';
import type { JudgeAction, JudgeState } from '../engine/judge/game';
import { loadJudge, saveJudge } from '../persistence/judge/save';
import type { Direction } from '../engine/trail/exploration';
import { nearby } from '../engine/trail/exploration';
import { TrailWorld } from '../rendering/TrailWorld';
import { JudgeMeters } from './JudgeMeters';
import { GameDialog } from './GameDialog';
import { QuoteCorner } from './QuoteCorner';
import { JudgeTutorial } from './JudgeTutorial';
import { useJudgeSound } from './useJudgeSound';
import '../styles/trail.css';
import '../styles/judge.css';
type Panel='tutorial'|'case'|'consequence'|'ending'|'objects'|'observation'|'places'|'record'|'settings'|'restart'|null;
const keys:Record<string,Direction>={ArrowUp:'north',w:'north',ArrowDown:'south',s:'south',ArrowLeft:'west',a:'west',ArrowRight:'east',d:'east'};
const endings={won:'The hearings are stayed',chaos:'The town breaks apart',condemned:'Condemned',compromised:'A life purchased with a lie'};
export default function JudgeApp(){
  const [loaded]=useState(()=>{const result=loadJudge();if(result.state.phase==='explore'){result.state.location='chamber';result.state.positions.chamber={...result.state.positions.chamber,...townMaps[0].spawn,direction:'south'};}return result;});const [state,setState]=useState(loaded.state);const current=useRef(state);
  const [introduced,setIntroduced]=useState(()=>{try{return localStorage.getItem('the-weight:judge:tutorial:v1')==='complete';}catch{return false;}});
  const [panel,setPanel]=useState<Panel>(!introduced?'tutorial':state.phase==='ended'?'ending':state.phase==='consequence'?'consequence':null);
  const [presentedDay,setPresentedDay]=useState(0);
  const [canSave,setCanSave]=useState(loaded.canSave);const [issue,setIssue]=useState(loaded.issue);
  const [selected,setSelected]=useState<string|null>(null);const [message,setMessage]=useState('Explore the town. Inspect records before you rule.');
  const [feedback,setFeedback]=useState('');const [reduced,setReduced]=useState(false);const [systemMotion,setSystemMotion]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);const [fullscreen,setFullscreen]=useState(false);
  const game=useRef<HTMLElement>(null);const world=useRef<HTMLElement>(null);const sound=useJudgeSound(state.hysteria,state.phase==='ended');
  const map=townMaps.find(m=>m.id===state.location)!;const position=state.positions[state.location];const item=map.interactions.find(i=>i.id===selected);const caseData=cases[state.day-1];const standing=judgeStanding(state);
  const hearingQuotes=panel==='case'?[caseData.quote]:panel==='consequence'||panel==='ending'?[...new Set([caseData.quote,...state.quotes])]:state.quotes;
  const quiet=reduced||systemMotion;
  const arriving=introduced&&!panel&&state.phase==='explore'&&presentedDay!==state.day&&state.location==='chamber';
  const arrivalComplete=useCallback(()=>{setPresentedDay(state.day);setPanel('case');setMessage('Your visitor is ready to speak. You can hear the case or adjourn to look for evidence.');},[state.day,setPresentedDay,setPanel,setMessage]);
  useEffect(()=>{world.current?.focus();const query=matchMedia('(prefers-reduced-motion: reduce)');const motion=()=>setSystemMotion(query.matches);const full=()=>setFullscreen(document.fullscreenElement===game.current);query.addEventListener('change',motion);document.addEventListener('fullscreenchange',full);return()=>{query.removeEventListener('change',motion);document.removeEventListener('fullscreenchange',full);};},[]);
  function store(next:JudgeState){if(canSave){const error=saveJudge(next);if(error){setIssue(error);setCanSave(false);}}current.current=next;setState(next);}
  function close(){setPanel(null);setFeedback('');requestAnimationFrame(()=>world.current?.focus());}
  function act(action:JudgeAction){const result=judgeTransition(current.current,action);if(result.error){setFeedback(result.error);setMessage(result.error);return;}store(result.state);setFeedback('');if(action.type==='decide'){setPanel(result.state.phase==='ended'?'ending':'consequence');setMessage('Your ruling is recorded.');}else if(action.type==='continue'){close();setMessage(`Day ${result.state.day}. The next petitioner is approaching your bench.`);}else if(action.type==='visit'){close();setMessage('You enter another part of town. No time passes.');}else if(action.type==='connect'){setFeedback('Connection saved. You can use this evidence in a hearing.');}}
  function inspect(id:string){if(current.current.phase!=='explore')return;act({type:'inspect',id});setSelected(id);setPanel('observation');setMessage('Observation recorded. No time passes.');}
  function walk(direction:Direction){if(panel||arriving||state.phase!=='explore')return;act({type:'move',direction});const objects=nearby(current.current.positions[state.location],map);setMessage(objects.length?`${objects[0].title} · Press E to inspect`:'Arrow keys / WASD: move · E: inspect');}
  function interact(){if(panel||arriving||state.phase!=='explore')return;const object=nearby(position,map)[0];if(object)inspect(object.id);else setMessage('Move beside a numbered object or use Objects to inspect by name.');}
  function hear(){setPanel(state.phase==='ended'?'ending':state.phase==='consequence'?'consequence':'case');}
  async function toggleFullscreen(){try{if(document.fullscreenElement===game.current)await document.exitFullscreen();else if(game.current?.requestFullscreen)await game.current.requestFullscreen();else setMessage('Fullscreen is unavailable. The game still fits this window.');}catch{setMessage('Fullscreen could not open. You can keep playing here.');}}
  function finishTutorial(){if(!introduced){try{localStorage.setItem('the-weight:judge:tutorial:v1','complete');}catch{/* Optional preference. */}setIntroduced(true);}setPanel(state.phase==='ended'?'ending':state.phase==='consequence'?'consequence':null);world.current?.focus();}
  const title=panel==='case'?`Day ${state.day} · ${caseData.title}`:panel==='consequence'?'The town responds':panel==='ending'?endings[state.ending!]:panel==='observation'?item?.title??'Observation':panel==='objects'?'Objects in this place':panel==='places'?'The town':panel==='record'?'The public record':panel==='restart'?'Begin a new term?':'Settings & help';
  return <main ref={game} className={`game-shell judge-shell ${state.hysteria>=80?'pressure-high':state.hysteria>=50?'pressure-rising':''} ${quiet?'quiet-motion':''}`} aria-label="The Weight: town judge" onKeyDown={e=>{if(panel||e.altKey||e.ctrlKey||e.metaKey||e.target instanceof HTMLElement&&e.target.closest('input,select,textarea,dialog'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(keys[key]){e.preventDefault();walk(keys[key]);}else if((key==='e'||key==='Enter'&&e.target===world.current)&&!e.repeat){e.preventDefault();interact();}}}>
    <header className="game-header"><h1>THE WEIGHT<span>A TOWN UNDER JUDGMENT</span></h1><div className="game-header-actions">{issue&&<button onClick={()=>setPanel('settings')}>Save warning</button>}<button onClick={toggleFullscreen} aria-label={fullscreen?'Exit fullscreen':'Enter fullscreen'}><svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5"/></svg><span>{fullscreen?'Exit fullscreen':'Fullscreen'}</span></button></div></header>
    <div className="judge-hud" aria-label="Town standing"><span>DAY <strong>{state.day} / {cases.length}</strong></span><JudgeMeters state={state}/>{state.shame.length>0&&<button className="shame-badge" onClick={()=>setPanel('record')}>Shame · {state.shame.length}</button>}</div>
    <section className="game-world" ref={world} tabIndex={0} aria-label={`Explore ${map.title}`} onPointerDown={e=>{if(e.target===e.currentTarget||e.target instanceof HTMLCanvasElement)world.current?.focus();}}>
      <div className="game-location"><span>LOCAL JUDGE · {state.phase==='ended'?'TERM ENDED':'NO CLOCK WHILE YOU READ'}</span><strong>{map.title}</strong></div>
      <div className="world-canvas"><TrailWorld map={map} state={position} reducedMotion={quiet} courtDay={state.day} arriving={arriving} onArrival={arrivalComplete}/></div>
      {!panel&&<QuoteCorner ids={state.quotes}/>}
      {state.phase==='explore'?<div className="game-touch" aria-label="Movement controls">{(['west','north','south','east'] as const).map((d,i)=><button key={d} aria-label={`Move ${d}`} disabled={arriving} onClick={()=>walk(d)}>{['←','↑','↓','→'][i]}</button>)}<button disabled={arriving} onClick={interact}>E · Interact</button></div>:<div className="game-context"><button onClick={hear}>{state.phase==='ended'?'Read outcome':'Read consequence'}</button></div>}
    </section>
    <p role="status" className="game-status">{arriving?'A petitioner enters the court and approaches you…':message}</p>
    <nav className="game-toolbar judge-toolbar" aria-label="Game menu"><button disabled={arriving} onClick={hear}>{state.phase==='explore'?'Resume hearing':'Read outcome'}</button><button disabled={arriving||state.phase!=='explore'} onClick={()=>setPanel('places')}>Places</button><button disabled={arriving||state.phase!=='explore'} onClick={()=>setPanel('objects')}>Objects</button><button disabled={arriving} onClick={()=>setPanel('record')}>Record</button><button onClick={()=>setPanel('settings')}>Settings</button></nav>
    {panel==='tutorial'&&<JudgeTutorial finish={finishTutorial} close={introduced?close:undefined}/>}
    {panel&&panel!=='tutorial'&&<GameDialog title={title} onClose={close} corner={<div className="hearing-status"><JudgeMeters state={state}/><QuoteCorner ids={hearingQuotes}/></div>}> 
      {panel==='case'&&<><p className="trail-kicker">TODAY’S CASE</p><p>{caseData.text}</p><p className="case-note"><strong>How it fits:</strong> {caseData.quoteConnection}</p><p className="ruling-hint">{rulingHint(state)}</p><div className="binary-choices"><button onClick={()=>act({type:'decide',choice:'defend',day:state.day,revision:state.revision})}>{caseData.defend}{caseData.kind==='accusation'&&state.connections.includes(caseData.proof)&&<small>Use the evidence you found</small>}</button><button onClick={()=>act({type:'decide',choice:'accuse',day:state.day,revision:state.revision})}>{caseData.accuse}</button></div><p className="case-note">You can adjourn to look for evidence before you decide. The case will wait.</p><button onClick={close}>Adjourn to investigate</button></>}
      {panel==='consequence'&&<><p>{state.consequence}</p><p>◇ {standing.reputation} · ⚑ {standing.hysteria}</p>{state.shame.some(s=>s.day===state.day)&&<p className="shame-note">You received a Shame badge for this ruling.</p>}<button onClick={()=>act({type:'continue'})}>Continue to the next day</button></>}
      {panel==='ending'&&<><p>{state.ending==='chaos'?'The accusations spread faster than the court can hear them. Neighbors turn on one another, and old grudges become excuses for arrests. The town falls into chaos.':state.ending==='condemned'&&state.reputation===0?'The elders accuse you of helping the suspects. No one dares to defend you. The court condemns you.':state.consequence}</p><p>{state.ending==='won'?'For now, no one else will be arrested on an unchecked accusation.':'On your next attempt, compare the records before you rule. Look for a chance to question accusers in public and let witnesses correct their statements.'}</p>{state.shame.length>0&&<p>Your Shame badges remain in the record{state.recanted.length?' alongside your public correction':''}.</p>}<button onClick={()=>setPanel('record')}>Review the public record</button><button onClick={()=>setPanel('restart')}>Begin a new term</button></>}
      {panel==='objects'&&<div className="trail-objects">{map.interactions.map((i,index)=><button key={i.id} onClick={()=>inspect(i.id)}>{index+1} · {i.title}<small>{state.evidence.includes(i.id)?'Recorded':'Inspect'}</small></button>)}</div>}
      {panel==='observation'&&item&&<><p>{item.body}</p><p className="case-note">This document was written for the game. It is not a passage from The Crucible.</p>{item.id==='docket'&&<button disabled={arriving} onClick={hear}>{state.phase==='explore'?'Resume hearing':'Read outcome'}</button>}<button onClick={()=>setPanel('record')}>Compare in the public record</button></>}
      {panel==='places'&&<><p>Choose where to go. The hearing will wait while you investigate.</p><div className="trail-objects">{townMaps.map(m=><button key={m.id} onClick={()=>act({type:'visit',location:m.id})}>{m.title}{m.id===state.location?' · You are here':''}</button>)}</div></>}
      {panel==='record'&&<><h3>Compare the evidence</h3><p>Read each pair of records and choose what they tell you. If you get it wrong, you can try again. Remember that a grudge does not prove guilt, and a copied statement is not a second witness.</p>{connections.map(c=><section className="record-connection" key={c.id}><h3>{c.title} {state.connections.includes(c.id)?'✓':''}</h3>{c.clues.map(id=>{const i=townMaps.flatMap(m=>m.interactions).find(i=>i.id===id)!;return <p key={id}><strong>{i.title}:</strong> {state.evidence.includes(id)?i.body:`Not read yet. Find it in ${c.location}.`}</p>;})}{state.connections.includes(c.id)?<p>{c.feedback}</p>:<div className="binary-choices"><button disabled={state.phase!=='explore'||!c.clues.every(id=>state.evidence.includes(id))} onClick={()=>act({type:'connect',id:c.id,correct:true})}>{c.correct}</button><button disabled={state.phase!=='explore'||!c.clues.every(id=>state.evidence.includes(id))} onClick={()=>act({type:'connect',id:c.id,correct:false})}>{c.wrong}</button></div>}</section>)}{feedback&&<p role="status">{feedback}</p>}<h3>Your progress</h3><p>Connected records: {state.connections.length}/3 · Public questioning: {state.openRecord?'opened':'not yet'} · Public witnesses: {state.publicWitness?'present':'not yet'}</p><h3>Shame badges</h3>{state.shame.length?state.shame.map((s,i)=><p className="shame-note" key={i}>Day {s.day}: {s.reason}{state.recanted.includes(i)?'. You corrected this in public, but the badge stays.':''}</p>):<p>You have not backed an accusation to protect yourself.</p>}<details><summary>Rulings</summary>{state.history.map(h=><p key={h.day}>Day {h.day} · {cases[h.day-1].title}: {h.choice==='defend'?cases[h.day-1].defend:cases[h.day-1].accuse}</p>)}</details><details><summary>Quotations encountered</summary>{state.seenQuotes.map(id=><section key={id}><QuoteCorner ids={[id]}/><p>{quotes[id].context}</p></section>)}<p className="case-note">These quotes use the wording supplied for the game. Check the act references against your class edition.</p></details></>}
      {panel==='settings'&&<>{issue&&<section><p role="alert">{issue}</p>{!canSave&&<button onClick={()=>{const error=saveJudge(state);setIssue(error);setCanSave(!error);}}>Replace only the judge save</button>}</section>}<button onClick={()=>setPanel('tutorial')}>Replay tutorial</button><label className="trail-motion"><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/>Reduce motion</label><button onClick={sound.toggle}>{sound.enabled?'Mute town pulse':'Enable town pulse'}</button><p>{sound.caption}</p><p>Arrow keys / WASD move. E inspects. Escape closes a popup. The top meters show Reputation and Hysteria from 0 to 100. Ruling results show each change in parentheses. Reputation at zero means condemnation; Hysteria at 100 means chaos. Time advances only when you rule.</p><button onClick={()=>setPanel('restart')}>Begin a new term</button></>}
      {panel==='restart'&&<><p>This replaces only your judge-game progress. Earlier game saves and settings are untouched.</p><div className="binary-choices"><button onClick={()=>{store(initialJudge());setPresentedDay(0);setSelected(null);close();setMessage('A new term begins. Investigate before ruling.');}}>Start a new term</button><button onClick={close}>Keep this term</button></div></>}
    </GameDialog>}
  </main>;
}
