import { useState } from 'react';
import { GameDialog } from './GameDialog';
import { QuoteCorner } from './QuoteCorner';
const lessons=[
  {title:'Your first day as judge',body:<><p>You live in a small, isolated town. Now you have been appointed its judge. Each day, someone comes to court with a rumor or an accusation. Some are frightened. Others want land, money, or revenge.</p><p>Try to stop the witch hunt without getting condemned or letting the town fall apart. The Reputation and Hysteria meters at the top show how your rulings affect the town. Both run from 0 to 100.</p><p>The people and cases in this game are invented. The quotations come from <em>The Crucible</em>. The opening quote describes violence against parents.</p></>},
  {title:'Explore the courthouse',body:<><p>Move with the <kbd>arrow keys</kbd> or <kbd>W A S D</kbd>. Stand beside a numbered object and press <kbd>E</kbd> or <kbd>Enter</kbd> to examine it. You can also use the touch buttons or choose an item from Objects.</p><p>Open Places to visit the chamber, records room, or petition gallery. Take as long as you need to look around.</p><p>Open Record to compare what you have found. Look for financial interests, copied testimony, and old disputes. These can help you question an accusation, but they do not prove that anyone is a witch.</p></>},
  {title:'What your choices cost',body:<><p>Every hearing gives you two choices. Defending someone hurts your reputation, especially if you have no evidence. Backing an accusation can protect you, but it raises Hysteria and earns you a <strong>Shame</strong> badge.</p><p>You are condemned if Reputation reaches zero. The town falls into chaos if Hysteria reaches 100. Trying to stay neutral will not keep you safe: the elders expect you to take their side.</p><p>Evidence makes a defense stronger. If you can get witnesses to speak openly and let the town read the records, you may be able to stop the accusations. Watch for chances to do that.</p></>},
  {title:'Receive your first visitor',body:<><p>A petitioner will walk up to your bench, and the hearing will open automatically. Choose Adjourn to investigate if you need more evidence. Start with the old rulebook, then look through the records room and gallery. You can retry a wrong evidence connection without a penalty.</p><p>Choose Resume hearing when you are ready to rule. Read what happens, then continue to the next day. Press Escape to close a popup without making a choice. Record keeps your evidence, rulings, Shame badges, and triggered quotes.</p><p>You can use fullscreen for the whole game. Settings lets you reduce motion or turn on music that speeds up as Hysteria rises. Progress saves automatically unless your browser blocks storage.</p></>},
];
export function JudgeTutorial({finish,close}:{finish:()=>void;close?:()=>void}) {const [step,setStep]=useState(0);return <GameDialog title={lessons[step].title} onClose={close??(()=>{})} dismissible={!!close} corner={step===0?<QuoteCorner ids={['intro']}/>:undefined}><p className="trail-kicker">HOW TO PLAY · {step+1} / {lessons.length}</p>{lessons[step].body}<div className="tutorial-navigation"><button disabled={step===0} onClick={()=>setStep(step-1)}>Previous</button>{step<lessons.length-1?<button onClick={()=>setStep(step+1)}>Next lesson</button>:<button onClick={e=>{e.currentTarget.closest('dialog')?.close();finish();}}>{close?'Return to game':'Take your seat'}</button>}</div></GameDialog>;}
