import { useState } from 'react';
import { GameDialog } from './GameDialog';

const lessons = [
  { title: 'Welcome to The Salem Trail', body: <><p>Play as John Proctor in an 8-bit journey inspired by Arthur Miller’s <em>The Crucible</em>. Explore a town shaped by fear, examine what people claim, and decide what to carry forward.</p><p>The journey, cart and supplies are invented for this adaptation. Public approval is not the same as being right.</p><h3>Your objective</h3><p>In this playable chapter, explore Parris’s house and reach the field boundary with stamina and cart condition above zero. Read observations carefully and manage your supplies along the way.</p><p>The wider story is about weighing evidence against rumor and protecting your integrity under pressure. The current journey visits Proctor farm and the meetinghouse yard before the field boundary. Full story scenes and later chapters are still in development.</p></> },
  { title: 'Move and interact', body: <><div className="tutorial-keys" aria-label="Movement keys"><kbd>↑</kbd><span><kbd>←</kbd><kbd>↓</kbd><kbd>→</kbd></span></div><p><strong>Arrow keys or W / A / S / D</strong> move John around a landmark. Walls and furniture can block the way.</p><p>Stand beside a numbered object and press <kbd>E</kbd> to inspect it. <kbd>Enter</kbd> also works while the world has focus. Watch the message above the game menu for nearby objects.</p><p>On a phone or tablet, tap the direction buttons and <strong>E · Interact</strong>. You can also use <strong>Objects</strong> to inspect any available object by name.</p></> },
  { title: 'Read, record and return', body: <><p>Inspections open a popup inside the game. Read the observation and expand <strong>Source and interpretation</strong> to learn how it relates to the play.</p><p>Press <kbd>Escape</kbd> or the close button to return to John. <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> move between popup controls; Enter or Space activates buttons.</p><p><strong>Journal</strong> keeps your observations and journey log. Reading, walking, opening menus and reviewing your journal cost no food or time. Take as long as you need.</p><p>Look for the difference between an observation, an allegation and an inference. A rumor is not proof.</p></> },
  { title: 'Prepare and travel', body: <><p>Open <strong>Journey</strong> to choose your route, pace and rations. The public road is 4 units long and costs 3 reputation on arrival. The detour is 6 units long with no arrival reputation cost.</p><p><strong>Careful / steady / forced</strong> pace advances 1 / 2 / 3 units per day. Faster travel uses more stamina and damages the cart more. Full rations use 2 food; sparse uses 1 food with extra stamina loss. Choosing no food costs still more stamina.</p><p>Read the forecast, then press <strong>Travel one day</strong>. A short final day still pays the full daily cost. Every travel or rest day raises town fear.</p><p>Travel is turn-based: waiting does not advance the journey. Encounters pause travel in a popup. Their costs are separate from the day already paid; reloading keeps the same choice. On the third leg, both routes meet a damaged bridge: wait with chosen rations, pay 3 coins for help, or ford for 10 cart and 5 stamina. You may skip the cart animation without changing the result.</p></> },
  { title: 'Keep the journey going', body: <><p>Watch the <strong>Day, Food, Stamina, Cart, Coins and Kits</strong> display. At a landmark, rest to recover stamina while consuming your chosen rations and a day; use a kit to repair the cart without spending a day.</p><p>At Proctor farm, buy 3 food for 1 coin or a repair kit for 3 coins. Food capacity is 40; kit capacity is 4. If you cannot afford a ration or purchase, choose an explicit alternative.</p><p>Zero stamina or cart condition ends the journey. Extreme town fear or lost public standing can also stop it. Serious risks ask for confirmation. Restore the last landmark checkpoint to prepare differently; this discards later choices but keeps the itinerary. Standing describes public judgment, not your moral worth.</p><p><strong>Settings</strong> offers reduced motion and this tutorial. The fullscreen button expands the game and its popups. Progress saves automatically when browser storage is available.</p><h3>Your first steps</h3><p>Move toward the hearth, press E to inspect it, then explore the other objects. When ready, open Journey and choose a route to Proctor farm.</p></> },
];

export function Tutorial({ onFinish, onClose }: { onFinish: () => void; onClose?: () => void }) {
  const [step, setStep] = useState(0);
  return <GameDialog title={lessons[step].title} onClose={onClose ?? (() => {})} dismissible={!!onClose}>
    <p className="trail-kicker" aria-live="polite">HOW TO PLAY · {step + 1} / {lessons.length}</p>
    <progress className="tutorial-progress" value={step + 1} max={lessons.length} aria-label="Tutorial progress" />
    {lessons[step].body}
    <div className="tutorial-navigation"><button disabled={step === 0} onClick={() => setStep(step - 1)}>Previous</button>{step < lessons.length - 1 ? <button onClick={() => setStep(step + 1)}>Next lesson</button> : <button onClick={event => { event.currentTarget.closest('dialog')?.close(); onFinish(); }}>{onClose ? 'Return to game' : 'Start game'}</button>}</div>
  </GameDialog>;
}
