import { describe, expect, it, vi, afterEach } from 'vitest';
import { connections, townMaps, cases } from '../../src/content/judge';
import { initialJudge, judgeTransition } from '../../src/engine/judge/game';
import type { JudgeState, JudgeAction } from '../../src/engine/judge/game';
import { validJudge, loadJudge, saveJudge, JUDGE_KEY } from '../../src/persistence/judge/save';
const act=(s:JudgeState,a:JudgeAction)=>{const r=judgeTransition(s,a);expect(r.error).toBeNull();expect(validJudge(r.state)).toBe(true);return r.state;};
function prepare(){let s=initialJudge();for(const m of townMaps){s=act(s,{type:'visit',location:m.id});for(const i of m.interactions)s=act(s,{type:'inspect',id:i.id});}for(const c of connections)s=act(s,{type:'connect',id:c.id,correct:true});return s;}
function run(mask:number,prepared=true){let s=prepared?prepare():initialJudge();while(s.phase!=='ended'){s=act(s,{type:'decide',choice:mask&(1<<(s.day-1))?'accuse':'defend',day:s.day,revision:s.revision});if(s.phase==='consequence')s=act(s,{type:'continue'});}return s;}
afterEach(()=>vi.unstubAllGlobals());
describe('town judge',()=>{
 it('has eight binary hearings and free investigation',()=>{expect(cases).toHaveLength(8);expect(cases.every(c=>c.defend&&c.accuse)).toBe(true);const s=prepare();expect([s.day,s.reputation,s.hysteria]).toEqual([1,62,30]);expect(s.connections).toHaveLength(3);});
 it('makes a discoverable public-record victory rare across every binary plan',()=>{const prepared=Array.from({length:256},(_,mask)=>run(mask));const blind=Array.from({length:256},(_,mask)=>run(mask,false));expect(prepared.filter(s=>s.ending==='won')).toHaveLength(5);expect(blind.filter(s=>s.ending==='won')).toHaveLength(0);expect(run(0).ending).toBe('won');expect(run(0,false).ending).toBe('condemned');expect(run(255).ending).toBe('chaos');});
 it('allows one early correction without erasing Shame; late accusations still fail',()=>{const s=run(1);expect(s.ending).toBe('won');expect(s.shame).toHaveLength(1);expect(s.recanted).toEqual([0]);expect(run(64).ending).toBe('condemned');});
 it('shows confession, neutrality, accusation and threshold quotations',()=>{expect(run(128).quotes).toContain('name');let s=prepare();for(let day=1;day<=4;day++){s=act(s,{type:'decide',choice:day===4?'accuse':'defend',day:s.day,revision:s.revision});if(day<4)s=act(s,{type:'continue'});}expect(s.quotes).toContain('neutral');s=initialJudge();for(let day=1;day<=3;day++){s=act(s,{type:'decide',choice:'accuse',day:s.day,revision:s.revision});if(day<3)s=act(s,{type:'continue'});}expect(s.quotes).toEqual(['accuse','hysteria']);});
 it('returns to the bench for the next petitioner without losing investigated evidence',()=>{let s=prepare();s=act(s,{type:'visit',location:'archive'});const evidence=[...s.evidence];s=act(s,{type:'decide',choice:'defend',day:s.day,revision:s.revision});s=act(s,{type:'continue'});expect(s.location).toBe('chamber');expect(s.positions.chamber).toMatchObject(townMaps[0].spawn);expect(s.evidence).toEqual(evidence);expect(s.day).toBe(2);});
 it('rejects duplicate decisions and connections without inspected evidence',()=>{const s=initialJudge();expect(judgeTransition(s,{type:'connect',id:'motive',correct:true}).error).toBeTruthy();const a:JudgeAction={type:'decide',choice:'accuse',day:1,revision:0};const next=act(s,a);expect(judgeTransition(next,a).state).toBe(next);expect(s.history).toHaveLength(0);});
 it('rejects corrupt positions and preserves unreadable saves until explicitly replaced',()=>{const s=initialJudge();s.positions.chamber.x=-1;expect(validJudge(s)).toBe(false);const setItem=vi.fn();vi.stubGlobal('localStorage',{getItem:()=>'{broken',setItem});expect(loadJudge().canSave).toBe(false);expect(setItem).not.toHaveBeenCalled();expect(saveJudge(initialJudge())).toBeNull();expect(setItem.mock.calls[0][0]).toBe(JUDGE_KEY);});
 it('rejects saves whose meters disagree with their last ruling',()=>{const s=run(0);s.reputation++;expect(validJudge(s)).toBe(false);const fresh=initialJudge();fresh.hysteria=90;expect(validJudge(fresh)).toBe(false);});
 it('rejects a final hearing saved as a continuable consequence',()=>{const s=run(0);s.phase='consequence';s.ending=null;expect(validJudge(s)).toBe(false);});
 it('rejects inherited object properties as quotation IDs',()=>{const s=initialJudge();Object.assign(s,{quotes:['toString'],seenQuotes:['toString']});expect(validJudge(s)).toBe(false);});
 it('rejects a condemnation before a threshold or final refusal',()=>{const s=act(initialJudge(),{type:'decide',choice:'defend',day:1,revision:0});s.phase='ended';s.ending='condemned';expect(validJudge(s)).toBe(false);});
 it('handles storage denial without throwing',()=>{vi.stubGlobal('localStorage',{getItem:()=>{throw Error('denied');},setItem:()=>{throw Error('quota');}});expect(loadJudge().issue).toBeTruthy();expect(saveJudge(initialJudge())).toBeTruthy();});
});
